# -*- coding: utf-8 -*-
"""Copy of Least_squares_II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WjGdfZ1RoeeMP-lMiootxO5X8WHMdm5s

#**Lab 7 - Least squares II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab7"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Trevor"

last_name="Ashby"

# Enter your Math 215 section number in between the quotation marks. 

section_number="003"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER! 

BYUNetID="trashby"

"""**Import the data set**

The simplest way to load the data into Colab is to first download it as a .csv file to your local computer by clicking the link

https://drive.google.com/uc?export=download&id=1iFTaBmnv1X66BO9cV_RP7OxvUr9dNJ-l

This will bring up the option to download the data as a .csv file. Once it has finished downloading, execute the following cell.  This will bring up an option to choose files from your local computer to upload to Google Colab (note that the cell will not finish executing until you download the file).  Push the "Browse" or "Choose Files" button, and locate the file titled "Lab7data.csv" on your local computer.
"""

from google.colab import files
import io

uploaded = files.upload()

"""Now that we've uploaded the file, we will convert it to a NumPy array called "signal_data".  We will import NumPy here as usual, as well as another package called Pandas which we use to import the csv file and create the array."""

import numpy as np
import pandas as pd

df = pd.read_csv(io.StringIO(uploaded['Lab7data.csv'].decode('utf-8')))
signal_data=df.values
signal_data

"""**Problem 1**"""

T= signal_data[:,0]         # Replace the value of 0 with the NumPy vector that contains all of the time values in the array signal_data (the first column).

Y= signal_data[:,1]           # Replace the value of 0 with the NumPy vector that contains all of the signal amplitude values in the array signal_data (the second column).

import matplotlib.pyplot as plt
x = T
y = Y
def create_plots1():
  plt.plot(x, y) # Put all of your code to create the plots here.
  plt.show()
  return None
# Create the plot here of the data in the vectors T and Y.

"""**Problem 2**"""

# This function returns the row [1,cos(t),sin(t), cos(2*t), sin(2*t) , ... , cos(n*t), sin(n*t)] of our matrix X.
def row_func(t,n):
  L = [f(t*k) for k in range(1,(n+1)) for f in [np.cos,np.sin]]
  L.insert(0,1)
  # Put your code here.
  return L # Put your return value here.

"""**Problem 3**"""

# This function returns the matrix X, which we call the design matrix.

def design_matrix(n):
  result = [row_func(t, n) for t in T]
  # Put your code here.
  result = np.array(result)
  return result # Put your return value here.

"""**Problem 4**"""

X2= design_matrix(2)    # Replace the value of 0 with the NumPy array that is returned from the function call design_matrix(2).

"""**Problem 5**"""

# Replace all of the 0 values with the NumPy matrices and vectors requested in Problem 5.
XT = np.transpose(X2)
normal_coef2= np.matmul(XT, X2)

normal_vect2= np.matmul(XT, Y)

beta2= np.linalg.solve(normal_coef2, normal_vect2)

"""**Problem 6**"""

# This is our function which approximates the signal strength when n=2.

def f2(t):
  result = np.dot(beta2, row_func(t,2))
  # Put your code here.
  return result # Put your return value here.

"""**Problem 7**"""

# Create your plot here.  
vf2=np.vectorize(f2)
plt.plot(T,Y,'r.')
plt.plot(T,vf2(T), 'b-')
plt.show()

"""**Problem 8**"""

MSE2= (1/629)*(np.linalg.norm((np.matmul(X2,beta2))-Y)**2)    # Replace the 0 value with the mean square error you compute in Problem 8.

"""**Problem 9**"""

# Replace the 0 values with the values requested in Problem 9.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.
#X10 = design_matrix(10)
#XT10 = np.transpose(X10)
#normal_coef10= np.matmul(XT10, X10)
#normal_vect10= np.matmul(XT10, Y)
#beta10 = np.linalg.solve(normal_coef10, normal_vect10)

#def f10(t):
#  result = np.dot(beta10, row_func(t,10))
  # Put your code here.
#  return result


#MSE10= (1/629)*(np.linalg.norm((np.matmul(X10,beta10))-Y)**2)

#pred10= f10(0.105)
MSE10= 0.009348751458203413
pred10= 0.5087757565416515

"""**Problem 10**"""

# Replace the 0 values with the values requested in Problem 10.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.
#X100 = design_matrix(100)
#XT100 = np.transpose(X100)
#normal_coef100= np.matmul(XT100, X100)
#normal_vect100= np.matmul(XT100, Y)
#beta100 = np.linalg.solve(normal_coef100, normal_vect100)

#def f100(t):
#  result = np.dot(beta100, row_func(t,100))
#  return result

MSE100= 0.0014547562364331283

pred100= 0.5089902472113171

"""**Problem 11**"""

# Replace the 0 values with the values requested in Problem 11.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.
#X1000 = design_matrix(1000)
#XT1000 = np.transpose(X1000)
#normal_coef1000= np.matmul(XT1000, X1000)
#normal_vect1000= np.matmul(XT1000, Y)
#beta1000 = np.linalg.solve(normal_coef1000, normal_vect1000)

#def f1000(t):
#  result = np.dot(beta1000, row_func(t,1000))
#  return result

#MSE1000= (1/629)*(np.linalg.norm((np.matmul(X1000,beta1000))-Y)**2)

#pred1000= f1000(0.105)

MSE1000= 2.097137515870964e-28
pred1000= -4.142207346927405

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file.  In the "File" menu select "Download .py".  The resulting file can then be uploaded to https://linearalgebra.byu.edu for grading.
"""